---
- name: Ensure hostname resolution
  lineinfile:
    dest=/etc/hosts
    regexp='^127.0.1.1'
    line="127.0.1.1{{'\t'}}{{ ansible_hostname }}"

- name: Update package manager
  apt:
    update_cache=yes
    cache_valid_time=43200
  when: "'apt' == ansible_pkg_mgr"

- name: Base packages
  action: " {{ ansible_pkg_mgr }}
    {{ 'pkg' if ansible_pkg_mgr == 'apt' else 'name' }}=ntp
    state=present"
